version: '3.8'

services:
  ### PostgreSQL Database ###
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: UserIPTrackerDB
    ports:
      - "5432:5432"

  ### Redis Cache ###
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  ### Kafka & Zookeeper ###
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  ### .NET API ###
  useriptracker-api:
    build:
      context: .
      dockerfile: API/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQL: "Host=postgres;Database=UserIPTrackerDB;Username=admin;Password=password"
      Redis__Host: "redis:6379"
      Kafka__BootstrapServers: "kafka:9092"
